### ISSUE TITLE
Dependency List Needed [FEATURE]

### ISSUE THREAD

**Issue by HeloiseS** [Deech08/whampy#11]
I noticed the [Making Interactive Maps with Whampy tutorial ](https://whampy.readthedocs.io/en/latest/click_maps.html) also requires cartopy, this time explicitly. Since it seems important to core features of the utilities you produced it should either be added to the dependencies in the pip install or explicitly stated in the READ ME. 

(also your interactive map is absolute bomb - really awesome :smiley: )

-----
*This issue is part of the current JOSS-review of whampy ( [#1940](https://github.com/openjournals/joss-reviews/issues/1940) )*

**Comment by Deech08** [comment]
I'm glad you like the interactive map!

As for cartopy - I originally had it as a dependency and removed it because it sometimes causes install issues (especially on linux machines apparently). I was favoring making it an optional dependency. Would it suffice to add more specific statements mentioning on that tutorial that this feature will only work if you install an optional other package (cartopy)?

**Comment by HeloiseS** [comment]
I totally get that - I did have to fiddle a little to install cartopy. I think it is important to make it super clear that this is optional and something that the user needs to do. Maybe even sign post them to resources to install cartopy and its dependencies. This may feel like over kill but I'm trying to keep in mind junior scientists or people who are new to python and don't have the same reflexes we do in terms of debugging. :)
